version: "3.9"
services:
  dev:
    container_name: dev_container
    build:
      context: ..
      dockerfile: docker/.
    image: dev-container:0.0.1
    stdin_open: true
    tty: true
    command: /bin/sh